services:
  postgres:
    profiles: ['pg']
    image: postgres:16
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: contract_testing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  prism:
    profiles: ['prism']
    image: stoplight/prism
    command: 'mock -d --json-schema-faker-fillProperties=false /tmp/openapi.json'
    volumes:
      - ./openapi.json:/tmp/openapi.json:ro
    ports:
      - '8080:4010'

volumes:
  postgres_data:

