services:
  prism:
    profiles: ['prism']
    image: stoplight/prism
    command: 'mock -d -h 0.0.0.0 --json-schema-faker-fillProperties=false /tmp/homesapi.json'
    volumes:
      - ./homesapi.json:/tmp/homesapi.json:ro
    ports:
      - '4010:4010'
